# Generated by Django 3.1 on 2020-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=8)),
                ('guests', models.CharField(choices=[('2 guests', '2 guests'), ('3 guests', '3 guests'), ('4 guests', '4 guests'), ('5 guests', '5 guests'), ('6 guests', '6 guests'), ('7 guests', '7 guests'), ('8 guests', '8 guests'), ('9 guests', '9 guests'), ('10 guests', '10 guests'), ('11 guests', '11 guests'), ('12 guests', '12 guests'), ('13 guests', '13 guests'), ('14 guests', '14 guests'), ('15 guests', '15 guests'), ('16 guests', '16 guests'), ('17 guests', '17 guests'), ('18 guests', '18 guests'), ('19 guests', '19 guests'), ('20 guests', '20 guests')], max_length=12)),
            ],
        ),
    ]
