# Generated by Django 3.1 on 2020-08-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200821_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='guests',
            field=models.CharField(choices=[('2 guests', '2 guests'), ('3 guests', '3 guests'), ('4 guests', '4 guests'), ('5 guests', '5 guests'), ('6 guests', '6 guests'), ('7 guests', '7 guests'), ('8 guests', '8 guests'), ('9 guests', '9 guests'), ('10 guests', '10 guests'), ('11 guests', '11 guests'), ('12 guests', '12 guests'), ('13 guests', '13 guests'), ('14 guests', '14 guests'), ('15 guests', '15 guests'), ('16 guests', '16 guests'), ('17 guests', '17 guests'), ('18 guests', '18 guests'), ('19 guests', '19 guests'), ('20 guests', '20 guests')], default='2 guests', max_length=12),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='time',
            field=models.CharField(choices=[('9:00 AM', '9:00 AM'), ('9:30 AM', '9:30 AM'), ('10:00 AM', '10:00 AM'), ('10:30 AM', '10:30 AM'), ('11:00 AM', '11:00 AM'), ('11:30 AM', '11:30 AM'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('1:00 PM', '1:00 PM'), ('1:30 PM', '1:30 PM'), ('2:00 PM', '2:00 PM'), ('2:30 PM', '2:30 PM'), ('3:00 PM', '3:00 PM'), ('3:30 PM', '3:30 PM'), ('4:00 PM', '4:00 PM'), ('4:30 PM', '4:30 PM'), ('5:00 PM', '5:00 PM'), ('5:30 PM', '5:30 PM'), ('6:00 PM', '6:00 PM'), ('6:30 PM', '6:30 PM'), ('7:00 PM', '7:00 PM'), ('7:30 PM', '7:30 PM'), ('8:00 PM', '8:00 PM'), ('8:30 PM', '8:30 PM'), ('9:00 PM', '9:00 PM'), ('9:30 PM', '9:30 PM'), ('10:00 PM', '10:00 PM')], default='7:00 PM', max_length=8),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customer')),
            ],
        ),
    ]
