# Generated by Django 3.1 on 2020-08-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_dietary_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dietary_tags', models.ManyToManyField(to='pages.Dietary')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
