# Generated by Django 3.1 on 2020-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200830_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='course',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Side', 'Side'), ('Dessert', 'Dessert')], max_length=50),
        ),
    ]
