# Generated by Django 3.1 on 2020-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200830_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, to='pages.Dietary'),
        ),
    ]
